name: MultiGames
author: Dams333
version: 1.0.0
main: ch.dams333.multiGames.MultiGames
load: startup
commands:
  valid:
    description: Valide l'inventaire de départ
    permission: multigames.admin
  debugstart:
    description: Demarre la partie en mode 'debug'
    permission: multigames.admin